function M = CoordSys2D(la,lt,va)

M = [[la+lt*cos(pi-va),lt*sin(pi-va)]',...
[la,0]',...
[la+lt*cos(pi+va),lt*sin(pi+va)]',...
[la,0]',...
[0,0]',...
[0,la]',...
[lt*cos(3*pi/2-va),la+lt*sin(3*pi/2-va)]',...
[0,la]',...
[lt*cos(3*pi/2+va),la+lt*sin(3*pi/2+va)]'];
% ,...
% [0,la,0]',...
% [0,0,0]',...
% [0,0,la]',...
% [lt*cos(3*pi/2-va),0,la+lt*cos(pi-va)]',...
% [0,0,la]',...
% [lt*cos(3*pi/2+va),0,la+lt*cos(pi+va)]']; %,...
% [0,0,la]',...
% [0,lt*cos(3*pi/2-va),la+lt*cos(pi-va)]',...
% [0,0,la]',...
% [0,lt*cos(3*pi/2+va),la+lt*cos(pi+va)]'];


% M = [[la+lt*cos(pi-va),lt*sin(pi-va),0]',...
% [la,0,0]',...
% [la+lt*cos(pi+va),lt*sin(pi+va),0]',...
% [la,0,0]',...
% [la+lt*cos(pi-va),0,lt*sin(pi-va)]',...
% [la,0,0]',...
% [la+lt*cos(pi+va),0,lt*sin(pi+va)]',...
% [la,0,0]',...
% [0,0,0]',...
% [0,la,0]',...
% [lt*cos(3*pi/2-va),la+lt*sin(3*pi/2-va),0]',...
% [0,la,0]',...
% [lt*cos(3*pi/2+va),la+lt*sin(3*pi/2+va),0]',...
% [0,la,0]',...
% [0,la+lt*sin(3*pi/2-va),lt*sin(pi-va)]',...
% [0,la,0]',...
% [0,la+lt*sin(3*pi/2+va),lt*sin(pi+va)]',...
% [0,la,0]',...
% [0,0,0]',...
% [0,0,la]',...
% [lt*cos(3*pi/2-va),0,la+lt*cos(pi-va)]',...
% [0,0,la]',...
% [lt*cos(3*pi/2+va),0,la+lt*cos(pi+va)]',...
% [0,0,la]',...
% [0,lt*cos(3*pi/2-va),la+lt*cos(pi-va)]',...
% [0,0,la]',...
% [0,lt*cos(3*pi/2+va),la+lt*cos(pi+va)]'];